accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': 'index'}, name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
]

main/urls.py
from django.urls import path, include
from main import views


urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.AnniversaryList.as_view(), name='list'),
    path('create/', views.AnniversaryCreate.as_view(), name='create'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import UserManager, AbstractUser


class AccountManager(UserManager):
    pass


class LoveUser(AbstractUser):
    objects = AccountManager()
    password2 = models.CharField(max_length=128, null=False)

main/models.py
from django.db import models
from phone_field import PhoneField


class AnniversaryPosts(models.Model):
    title = models.CharField(max_length=100, verbose_name='기념일 제목')
    content = models.CharField(max_length=500, verbose_name='메시지 내용')
    Anniversary_date = models.DateField('기념일')
    Anniversary_email = models.EmailField(blank=True)
    Anniversary_phone = PhoneField(blank=True)

    class Meta:
        ordering = ['Anniversary_date']

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import LoveUser
from django.core.mail import EmailMessage
from rest_framework import status
from rest_framework.response import Response
from django.template.loader import get_template


class LoverUserCreationForm(UserCreationForm):
    class Meta:
        model = LoveUser
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {
            'username': '</br>150자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다.',
            'email': '</br>Ex) example@example.com',
        }

    def save(self, commit=True):
        user = super(LoverUserCreationForm, self).save(commit=True) # 본인의 부모를 호출해서 저장하겠다.
        if commit:
            email = user.email
            if email is not None:
                subject = 'ANNIVERSARY Alarm 회원가입을 축하합니다!'
                message = 'Google SMTP에서 발송되었습니다.'
                mail = EmailMessage(subject, message, to=[email])
                mail.send()
                return Response(status=status.HTTP_200_OK)
            else:
                return Response(status=status.HTTP_400_BAD_REQUEST)
            user.save()
        return user


class AccountChangeForm(UserChangeForm):
    class Meta:
        model = LoveUser
        fields = UserChangeForm.Meta.fields


class LoginForm(forms.ModelForm):
    class Meta:
        model = LoveUser
        fields = ['username', 'password']
        labels = {
            'password': '비밀번호',
        }
        widgets = {
            'password': forms.PasswordInput(),
        }
        help_texts = {
            'username': '</br>150자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다.'
        }

accounts/views.py
from django.shortcuts import render, redirect
from .forms import LoverUserCreationForm, LoginForm
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth import login as dj_login, authenticate


class UserCreateView(CreateView): # 회원가입
    form_class = LoverUserCreationForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('login')


def login(request): # 로그인
    if request.method == "POST":
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            dj_login(request, user)
            return redirect('index')
        else:
            return render(request, 'accounts/login.html', {
                'error': '로그인 실패'
            })
    else:
        form = LoginForm()
        return render(request, 'accounts/login.html', {
            'form': form
        })
    return render(request, 'accounts/login.html')

main/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from main.models import AnniversaryPosts


def index(request):

    return render(request, 'main/index.html')


class AnniversaryList(ListView):
    model = AnniversaryPosts
    fields = '__all__'
    template_name = 'main/anniversary_list.html'


class AnniversaryCreate(CreateView):
    model = AnniversaryPosts
    fields = '__all__'
    template_name = 'main/anniversary_create.html'
    success_url = '/list'

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}
    로그인
{% endblock %}


{% block content %}
    <div style="margin-top: 50px; margin-bottom:50px;">
        <div class="container" style="border: solid 1px; padding-top: 30px; padding-bottom: 50px">
            <h3 class="text-center text-info">로그인</h3>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <center>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-info btn-md" value="로그인">
                    </div>
                </center>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/registration_verification.html
<table style="box-sizing: border-box; min-height: 150px; padding-top: 5px; padding-right: 5px; padding-bottom: 5px; padding-left: 5px; width: 100%; height: 100%; background-color: rgb(234, 236, 237); font-family: Arial Black, Gadget, sans-serif;" width="100%" height="100%" bgcolor="rgb(234, 236, 237)">
  <tbody style="box-sizing: border-box;">
    <tr style="box-sizing: border-box; vertical-align: top;" valign="top">
      <td style="box-sizing: border-box;">
        <table style="box-sizing: border-box; font-family: Helvetica, serif; min-height: 150px; padding-top: 5px; padding-right: 5px; padding-bottom: 5px; padding-left: 5px; margin-top: auto; margin-right: auto; margin-bottom: auto; margin-left: auto; height: 0px; width: 90%; max-width: 550px;" width="90%" height="0">
          <tbody style="box-sizing: border-box;">
            <tr style="box-sizing: border-box;">
              <td style="box-sizing: border-box; vertical-align: top; font-size: medium; padding-bottom: 50px;" valign="top">
                <table style="box-sizing: border-box; min-height: 150px; padding-top: 5px; padding-right: 5px; padding-bottom: 5px; padding-left: 5px; margin-bottom: 20px; height: 0px;" height="0">
                  <tbody style="box-sizing: border-box;">
                    <tr style="box-sizing: border-box;">
                      <td style="box-sizing: border-box; background-color: rgb(255, 255, 255); overflow-x: hidden; overflow-y: hidden; border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; text-align: center;" bgcolor="rgb(255, 255, 255)" align="center">
                        <table style="box-sizing: border-box; width: 100%; min-height: 150px; padding-top: 5px; padding-right: 5px; padding-bottom: 5px; padding-left: 5px; height: 0px; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; border-collapse: collapse;" width="100%" height="0">
                          <tbody style="box-sizing: border-box;">
                            <tr style="box-sizing: border-box;">
                              <td style="box-sizing: border-box; font-size: 13px; line-height: 20px; color: rgb(111, 119, 125); padding-top: 10px; padding-right: 20px; padding-bottom: 0px; padding-left: 20px; vertical-align: top;" valign="top">
                                <h1 style="box-sizing: border-box; font-size: 25px; font-weight: 300; color: rgb(68, 68, 68);">
                                  <span style="box-sizing: border-box; font-family: Arial,Helvetica,sans-serif;">가입을 환영합니다.!!</span>
                                </h1>
                                <p style="box-sizing: border-box;">
                                  <span style="box-sizing: border-box; font-family: Arial,Helvetica,sans-serif;">회원님이 가입하신 것이 맞다면 아래 "인증하기" 버튼을 눌러서 인증해주세요. 가입하신 적이 없을 경우 인증하기를 누르지 마시고 무시하세요.</span>
                                </p>
                                <table style="box-sizing: border-box; margin-top: 0px; margin-right: auto; margin-bottom: 10px; margin-left: auto; padding-top: 5px; padding-right: 5px; padding-bottom: 5px; padding-left: 5px; width: 100%;" width="100%">
                                  <tbody style="box-sizing: border-box;">
                                    <tr style="box-sizing: border-box;">
                                      <td style="box-sizing: border-box; padding-top: 20px; padding-right: 0px; padding-bottom: 20px; padding-left: 0px; text-align: center;" align="center">
                                        <a href="{{ url }}" class="button" style="box-sizing: border-box; font-size: 16px; padding-top: 10px; padding-right: 20px; padding-bottom: 10px; padding-left: 20px; background-color: rgb(217, 131, 166); color: rgb(255, 255, 255); text-align: center; border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; font-family: Arial, Helvetica, sans-serif; font-weight: 500; text-decoration: underline;">인증하기</a>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block title %}
    회원가입
{% endblock %}


{% block content %}
    <div style="margin-top: 50px; margin-bottom:50px;">
        <div class="container" style="border: solid 1px; padding-top: 30px; padding-bottom: 50px">
            <h3 class="text-center text-info">회원가입</h3>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <center>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-info btn-md" value="가입" onclick="">
                    </div>
                </center>
                <script>
                    {% if form.errors %}
                        {% for f in form %}
                            {% for e in f.errors %}
                                alert('{{ e | escape }}')
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                </script>
            </form>
        </div>
    </div>
{% endblock %}

main/templates/main/anniversary_create.html
{% extends 'base.html' %}
{% block title %}
    ANNIVERSARY WRITING
{% endblock %}
{% block content %}
    <!-- Contact -->
    <section class="page-section" id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading text-uppercase">Anniversary Writing</h2>
                    <h3 class="section-subheading text-muted">사랑하는 사람의 기념일을 기록하세요, 기념일이 되면 문자와 메일을 보내드립니다!</h3>
                </div>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                {#                {{ form.as_p }}#}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input class="form-control" id="id_Anniversary_date" type="text"
                                           placeholder="기념일 Datetime"
                                           required=""
                                           data-validation-required-message="Please enter your name."
                                           name="Anniversary_date" maxlength="254">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" id="id_Anniversary_email" type="email"
                                           placeholder="Your Email *"
                                           required=""
                                           data-validation-required-message="Please enter your email address."
                                           name="Anniversary_email" maxlength="254">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" id="id_Anniversary_phone_0" type="text"
                                           placeholder="Your Phone *"
                                           required=""
                                           data-validation-required-message="Please enter your phone number."
                                           name="Anniversary_phone_0" size="13">
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input class="form-control" id="id_title" placeholder="기념일 제목*"
                                           required=""
                                           data-validation-required-message="Please enter a message." name="title"
                                           maxlength="100">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                        <textarea class="form-control" id="id_content" placeholder="메시지 내용*"
                                                  required=""
                                                  data-validation-required-message="Please enter a message."
                                                  name="content" maxlength="500"></textarea>
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-12 text-center">
                                <div id="success"></div>
                                <input id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase"
                                       type="submit" value="Send Message">™
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

main/templates/main/anniversary_list.html
{% extends 'base.html' %}
{% block title %}
    ANNIVERSARY LIST
{% endblock %}
{% block content %}
    <!-- ANNIVERSARY LISt -->
    <section class="page-section" id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading text-uppercase">Anniversary List</h2>
                    <h3 class="section-subheading text-muted">작성한 기념일 목록을 볼 수 있습니다.</h3>
                </div>
            </div>
            {% for list in object_list %}
                <div class="row text-center">
                    <div class="col">
          <span class="fa-stack fa-4x">
            <i class="fas fa-circle fa-stack-2x text-primary"></i>
              <i class="fas fa-grin-hearts fa-stack-1x fa-inverse"></i>
          </span>
                        <h4 class="service-heading">{{ list.title }}</h4>
                        <p class="text-muted">{{ list.content }}</p>
                        <p class="text-muted">{{ list.Anniversary_date }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

main/templates/main/index.html
{% extends 'base.html' %}
{% block title %}HOME{% endblock %}


</head>

<body>
{% block content %}
    <!-- Services 소개 -->
    <section class="page-section" id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading text-uppercase">Services</h2>
                    <h3 class="section-subheading text-muted">사랑하는 사람의 기념일을 입력하고, 이메일, 문자 알람을 받아보세요!</h3>
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
          <span class="fa-stack fa-4x">
            <i class="fas fa-circle fa-stack-2x text-primary"></i>
            <i class="far fa-envelope fa-stack-1x fa-inverse"></i>
          </span>
                    <h4 class="service-heading">E-Mail</h4>
                    <p class="text-muted">회원님께서 입력한 메세지 내용이 <br>상대방의 이메일로 전송됩니다!!</p>
                </div>
                <div class="col-md-4">
          <span class="fa-stack fa-4x">
            <i class="fas fa-circle fa-stack-2x text-primary"></i>
            <i class="fas fa-sms fa-stack-1x fa-inverse"></i>
          </span>
                    <h4 class="service-heading">SMS</h4>
                    <p class="text-muted">회원님께서 입력한 메세지 내용이 <br>상대방에게 문자로 전송됩니다!</p>
                </div>
                <div class="col-md-4">
          <span class="fa-stack fa-4x">
            <i class="fas fa-circle fa-stack-2x text-primary"></i>
            <i class="fas fa-lock fa-stack-1x fa-inverse"></i>
          </span>
                    <h4 class="service-heading">Security</h4>
                    <p class="text-muted">ANNIVERSARY Alarm이 <br> 제공하는 서비스는 안전합니다!!</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact me -->
    <section class="bg-light page-section" id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading text-uppercase">Contact</h2>
                    <h3 class="section-subheading text-muted">Contact Me!!</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a class="portfolio-link" data-toggle="modal" href="#portfolioModal1">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fas fa-plus fa-3x"></i>
                            </div>
                        </div>
                    </a>
                    <div class="portfolio-caption">
                        <h4><a href="https://github.com/2044smile" target="_blank">Github</a></h4>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a class="portfolio-link" data-toggle="modal" href="#portfolioModal2">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fas fa-plus fa-3x"></i>
                            </div>
                        </div>
                    </a>
                    <div class="portfolio-caption">
                        <h4>E-mail</h4>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a class="portfolio-link" data-toggle="modal" href="#portfolioModal3">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fas fa-plus fa-3x"></i>
                            </div>
                        </div>
                    </a>
                    <div class="portfolio-caption">
                        <h4><a href="http://newbiecs.tistory.com/" target="_blank">Blog</a></h4>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
</body>

</html>

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- config core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet'
          type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/agency.min.css' %}" rel="stylesheet">
    <style>
        {% block style %}
        {% endblock %}
    </style>
</head>

<body id="page-top">
{% block navbar %}
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="/">ANNIVERSARY Alarm</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'list' %}">ANNIVERSARY List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create' %}">Writing</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">{{ user.username }}님 환영합니다.</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}" onclick="alert('{{ user.username }}님 로그아웃 되었습니다.')">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signup' %}">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block header %}
    <!-- Header -->
    <header class="masthead">
        <div class="container">
            <div class="intro-text">
                <div class="intro-lead-in">Welcome To Our Studio!</div>
                <div class="intro-heading text-uppercase">It's Nice To Meet You</div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Your Website 2019</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li class="list-inline-item">
                            <a href="#">Privacy Policy</a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Contact form JavaScript -->
<script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
<script src="{% static 'js/contact_me.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'js/agency.min.js' %}"></script>

</body>
</html>